---
Date: 2021-10-26
aliases: ["Panic 和 Recover"]
---

# Metadata

**Title** :: Panic 和 Recover

**Author** :: #dPaulLai

**Classification** :: #Learn #Go #Basic

**Status** :: #🌞 

**Type** :: #Note

**Previous** ::

**ParentNode** :: [[Go 基礎教學]]

---

# Panic

**作用**

1. 停止当前函数运行
2. 一直向上返回,执行每一层的[[Study_dPaul/Golang/Go 基礎教學/1-8-1|Defer]]
3. 如果没有遇见[[Study_dPaul/Golang/Go 基礎教學/1-8-4#Recover|Recover]],则程序退出

# Recover

1. 仅在[[Study_dPaul/Golang/Go 基礎教學/1-8-1|Defer]]调用中使用
2. 获取[[Study_dPaul/Golang/Go 基礎教學/1-8-4#Panic|Painc]]的值
3. 如果无法处理,可以重新[[Study_dPaul/Golang/Go 基礎教學/1-8-4#Panic|Painc]]


# 示例

```go
package main  
  
import "fmt"  
  
func main() {  
	tryRecover1()  
	tryRecover2()  
}  
  
func tryRecover1() {  
	defer recoverDemo()  
	b := 0  
	a := 5 / b  
	fmt.Println(a)  
}  
  
func tryRecover2() {  
	defer recoverDemo()  
	panic(123)  
}  
  
func recoverDemo() {  
	r := recover()  
	if r == nil {  
		fmt.Println("r is nil")  
		return  
	}  
	if err, ok := r.(error); ok {  
		fmt.Println("Error occurred:", err)  
	} else {  
		panic(fmt.Sprintf("I don't know what to do: %v", r))  
	}
}
```

# Panic 与 Error

- Error : 意料之中 [ 文件打不开 ]
- Panic : 意料之外 [ 数组越界 ]

