---
Date: 2021-10-26
aliases: []
---

# Metadata

**Title** :: 服务器统一错误处理

**Author** :: #dPaulLai

**Classification** :: #Learn #Go #Basic

**Status** :: #🌞 

**Type** :: #Note

**Previous** ::

**ParentNode** :: [[Go 基礎教學]]

---

# 服务器统一错误处理


1. 先构建一个 Http 服务器,同时具备一个`/A`的API

	```go
	package main  

	import (  
	 "fmt"  
	 "net/http"
	)  

	func main() {  
		http.HandleFunc("/A", func(writer http.ResponseWriter, request *http.Request) {  
			fmt.Println("A") 
			_, _ = writer.Write([]byte("请求成功\n"))
		})
		// URL 为 http://127.0.0.1:8080
		err := http.ListenAndServe(":8080", nil)  
		if err != nil {  
			panic(err)  
		}
	}
	```
	访问该API时,会使服务器内部打印一句`A`

2. 强制让服务器内部发生错误
	```go
	package main  

	import (  
	 "errors"  
	 "net/http")  

	func main() {  
		http.HandleFunc("/A", func(writer http.ResponseWriter, request *http.Request) {  
			err := errors.New("故意产生异常")  
			panic(err)
			_, _ = writer.Write([]byte("请求成功\n"))
		})
		err := http.ListenAndServe(":8080", nil)  
		if err != nil {  
			panic(err)  
		}
	}
	```

	此时,发生异常时控制台将打印一下内容
	```bash
	2021/10/26 09:41:27 http: panic serving 127.0.0.1:61250: 故意产生异常
	goroutine 6 [running]:
	... ...
	... ...
	... ...
	created by net/http.(*Server).Serve
		C:/Program Files/Go/src/net/http/server.go:3033 +0x4e8

	```

	而前端也将返回 `org.apache.http.NoHttpResponseException: 127.0.0.1:8080 failed to respond`

3. 基础处理报错方式
	```go
	package main  

	import (  
	 "errors"  
	 "fmt" "net/http")  

	func main() {  
		http.HandleFunc("/A", func(writer http.ResponseWriter, request *http.Request) {  
			err := errors.New("故意产生异常")  
			if err != nil {  
				fmt.Println(err.Error())  
				_, _ = writer.Write([]byte(err.Error()))  
			} else {  
				_, _ = writer.Write([]byte("请求成功\n"))  
			} 
		}) 
		err := http.ListenAndServe(":8080", nil)  
		if err != nil {  
			panic(err)  
		}
	}
	```

	将每次产生出来的异常都进行捕获,然后做异常处理

	这个方法是可以解决异常问题,但是会显得非常的麻烦,且代码会非常冗余

4. 统一处理报错方式
	```go
	
	package main  

	import (  
	 "fmt"  
	 "net/http" "os")  

	func main() {  
		http.HandleFunc("/A", errWrapper(handleA))  
		err := http.ListenAndServe(":8080", nil)  
		if err != nil {  
			panic(err)  
		}
	}  

	func handleA(writer http.ResponseWriter, request *http.Request) error {  
		_, _ = writer.Write([]byte("请求成功\n"))  
		return userErrorImpl("故意产生异常")  
	}  

	// appHandler  
	type appHandler func(writer http.ResponseWriter, request *http.Request) error  

	// errWrapper 异常处理器  
	func errWrapper(handler appHandler) func(writer http.ResponseWriter, request *http.Request) {  
		return func(writer http.ResponseWriter, request *http.Request) {  
			err := handler(writer, request)  
			if err != nil {  
				// user error  
				if userErr, ok := err.(userError); ok {  
					fmt.Println(userErr.Message())  
					_, _ = writer.Write([]byte(userErr.Message()))  
					return  
				}  

				// system error  
				code := http.StatusOK  
				switch {  
				case os.IsNotExist(err):  
						code = http.StatusNotFound  
				case os.IsPermission(err):  
						code = http.StatusForbidden  
				default:  
						code = http.StatusInternalServerError  
				} 
				http.Error(writer, http.StatusText(code), code)  
			} 
		}
	}  

	// userError 定义一个接口  
	type userError interface {  
		error  
		Message() string  
	}  

	// userErrorImpl 基于 string 制作了一个用户错误  
	type userErrorImpl string  

	// Error 继承 userError
	func (e userErrorImpl) Error() string {  
		return e.Message()  
	}  

	// Message 继承 userError
	func (e userErrorImpl) Message() string {  
		return string(e)  
	}
	```

	所有的错误封装都可以在`errWrapper`中进行处理		
5. 统一处理报错(使用[[Study_dPaul/Golang/Go 基礎教學/1-8-4#Recover|Recover]])
	```go
	// errWrapper 异常处理器  
	func errWrapper(handler appHandler) func(writer http.ResponseWriter, request *http.Request) {  
		return func(writer http.ResponseWriter, request *http.Request) {  
			// panic  
			defer func() {  
				if r := recover(); r != nil {  
					log.Printf("Panic: %v", r)  
					http.Error(writer, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)  
			    }
			}()
			
			err := handler(writer, request)  
			if err != nil {  
				// user error  
				if userErr, ok := err.(userError); ok {  
					fmt.Println(userErr.Message())  
					_, _ = writer.Write([]byte(userErr.Message()))  
					return  
				}  

				// system error  
				code := http.StatusOK  
				switch {  
				case os.IsNotExist(err):  
						code = http.StatusNotFound  
				case os.IsPermission(err):  
						code = http.StatusForbidden  
				default:  
						code = http.StatusInternalServerError  
				} 
				http.Error(writer, http.StatusText(code), code)  
			} 
		}
	}  
	```
	
	添加Recover对未捕获的异常进行最终处理